services:
  namenode:
    image: apache/hadoop:3
    container_name: hadoop-namenode
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "8020:8020"
    environment:
      HADOOP_HOME: /opt/hadoop
      CLUSTER_NAME: gemparadar
    env_file:
      - hadoop.env
    volumes:
      - namenode_data:/tmp/hadoop-hadoop/dfs/name
    networks:
      - hadoop_net

  datanode:
    image: apache/hadoop:3
    container_name: hadoop-datanode
    hostname: datanode
    command: ["hdfs", "datanode"]
    environment:
      HADOOP_HOME: /opt/hadoop
    env_file:
      - hadoop.env
    volumes:
      - datanode_data:/tmp/hadoop-hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop_net

volumes:
  namenode_data: {}
  datanode_data: {}

networks:
  hadoop_net:
    external: true
    name: hadoop_net